print("Digite quatro valores inteiros")
a = int(input())
b = int(input())
c = int(input())
d = int(input())
m = (a + b + c + d) / 4
print("Media=",m)
print("Numeros menores que a media")
if a < m:print(a)
if b < m:print(b)
if c < m:print(c)
if d < m:print(d)
print("numeros maiores ou iguais a media")
if a >= m:print(a)
if b >= m:print(b)
if c >= m:print(c)
if d >= m:print(d)
